<center><h1><font color="red">DO NOT EDIT THIS CODE, THE FILE IS NOT FROM THIS DEVICE</font></h1></center>
<center><h1><font color="red">DO NOT EDIT THIS CODE, THE FILE IS NOT FROM THIS DEVICE</font></h1></center>
<center><h1><font color="red">DO NOT EDIT THIS CODE, THE FILE IS NOT FROM THIS DEVICE</font></h1></center>

In [5]:
import os
import re
import pdfplumber
import pandas as pd 
import numpy as np

In [56]:
os.chdir('..')

os.chdir('Data Files')

# Now file is in current directory
pdfpath = "/Users/apple/Desktop/Data Science/Data Files"

with pdfplumber.open("Union Budget_2021-22_0.pdf") as pdf:
    page = pdf.pages[2]   # page 3
    text = page.extract_text()


lines = text.split("\n")
lines = lines[20:43]
lines

['Change (Annualised)',
 'Actuals Budgeted Revised Budgeted',
 '(Actuals2019-20to BE',
 '2019-20 2020-21 2020-21 2021-22',
 '2021-22)',
 'Revenue Expenditure 23,50,604 26,30,145 30,11,142 29,29,000 12%',
 'Capital Expenditure 3,35,726 4,12,085 4,39,163 5,54,236 29%',
 'of which:',
 'Capital outlay 3,11,312 3,80,322 3,32,247 5,13,862 29%',
 'Loans 24,414 31,763 1,06,916 40,374 29%',
 'Total Expenditure 26,86,330 30,42,230 34,50,305 34,83,236 14%',
 'Revenue Receipts 16,84,059 20,20,926 15,55,153 17,88,424 3%',
 'Capital Receipts 68,620 2,24,967 46,497 1,88,000 66%',
 'of which:',
 'Recoveries of Loans 18,316 14,967 14,497 13,000 -16%',
 'Other receipts (including disinvestments) 50,304 2,10,000 32,000 1,75,000 87%',
 'Total Receipts (without borrowings) 17,52,679 22,45,893 16,01,650 19,76,424 6%',
 'Revenue Deficit 6,66,545 6,09,219 14,55,989 11,40,576 31%',
 '% of GDP 3.3% 2.7% 7.5% 5.1%',
 'Fiscal Deficit 9,33,651 7,96,337 18,48,655 15,06,812 27%',
 '% of GDP 4.6% 3.5% 9.5% 6.8%',
 'Primary Deficit 3,21,581 88,134 11,55,755 6,97,111 47%',
 '% of GDP 1.6% 0.4% 5.9% 3.1%']

In [57]:
data = []

for line in lines:
    
    nums = re.findall(r'-?[\d,.]+%?', line)
    
    # keep only rows with at least 4 numbers
    if len(nums) >= 4:
        
        # keep only first 5 numbers
        nums = nums[:5]
        
        category = re.sub(r'-?[\d,.]+%?', '', line).strip()
        
        data.append([category] + nums)

budget_21_22 = pd.DataFrame(data, columns=[
    "Category",
    "Actuals_2019-20",
    "Budgeted_2020-21",
    "Revised_2020-21",
    "Budgeted_2021-22",
    "Change"
])
budget_21_22["year"] = "2021-22"
budget_21_22 = budget_21_22.replace({",": "", "%": ""}, regex=True)

budget_21_22 =budget_21_22.drop(index=0)
budget_21_22.iloc[11,0]= "Revenue Deficit(% of GDP)"
budget_21_22.iloc[13,0]= "Fiscal Deficit(% of GDP)"
budget_21_22.iloc[15,0]= "Primary Deficit(% of GDP)"



budget_21_22

,Category,Actuals_2019-20,Budgeted_2020-21,Revised_2020-21,Budgeted_2021-22,Change,year
1,Revenue Expenditure,2350604,2630145,3011142,2929000,12,2021-22
2,Capital Expenditure,335726,412085,439163,554236,29,2021-22
3,Capital outlay,311312,380322,332247,513862,29,2021-22
4,Loans,24414,31763,106916,40374,29,2021-22
5,Total Expenditure,2686330,3042230,3450305,3483236,14,2021-22
6,Revenue Receipts,1684059,2020926,1555153,1788424,3,2021-22
7,Capital Receipts,68620,224967,46497,188000,66,2021-22
8,Recoveries of Loans,18316,14967,14497,13000,-16,2021-22
9,Other receipts (including disinvestments),50304,210000,32000,175000,87,2021-22
10,Total Receipts (without borrowings),1752679,2245893,1601650,1976424,6,2021-22
11,Revenue Deficit,666545,609219,1455989,1140576,31,2021-22
12,Revenue Deficit(% of GDP),3.3,2.7,7.5,5.1,NaN,2021-22
13,Fiscal Deficit,933651,796337,1848655,1506812,27,2021-22
14,Fiscal Deficit(% of GDP),4.6,3.5,9.5,6.8,NaN,2021-22
15,Primary Deficit,321581,88134,1155755,697111,47,2021-22
16,Primary Deficit(% of GDP),1.6,0.4,5.9,3.1,NaN,2021-22

In [58]:
# 2nd PDF
with pdfplumber.open(os.path.join(pdfpath, "Union Budget_2022-23.pdf")) as pdf:

    page=pdf.pages[2]
    text=page.extract_text()

lines = text.split("\n")
lines = lines[20:40]
lines

['Actuals Budgeted Revised Budgeted % change (RE 2021-22',
 '2020-21 2021-22 2021-22 2022-23 to BE 2022-23)',
 'Revenue Expenditure 30,83,519 29,29,000 31,67,289 31,94,663 0.9%',
 'Capital Expenditure 4,26,317 5,54,236 6,02,711 7,50,246 24.5%',
 'of which:',
 'Capital Outlay 3,15,826 5,13,862 5,47,457 6,10,189 11.5%',
 'Loans and Advances 1,10,491 40,374 55,255 1,40,057 153.5%',
 'Total Expenditure 35,09,836 34,83,236 37,70,000 39,44,909 4.6%',
 'Revenue Receipts 16,33,920 17,88,424 20,78,936 22,04,422 6.0%',
 'Capital Receipts 57,625 1,88,000 99,975 79,291 -20.7%',
 'of which:',
 'Recoveries of Loans 19,729 13,000 21,975 14,291 -35.0%',
 'Other receipts (including disinvestments) 37,897 1,75,000 78,000 65,000',
 'Total Receipts (excluding borrowings) 16,91,545 19,76,424 21,78,911 22,83,713 4.8%',
 'Revenue Deficit 14,49,599 11,40,576 10,88,352 9,90,241 -9.0%',
 '% of GDP 7.3% 5.1% 4.7% 3.8%',
 'Fiscal Deficit 18,18,291 15,06,812 15,91,089 16,61,196 4.4%',
 '% of GDP 9.2% 6.8% 6.9% 6.4%',
 'Primary Deficit 11,38,422 6,97,111 7,77,298 7,20,545 -7.3%',
 '% of GDP 5.8% 3.1% 3.3% 2.8%']

In [59]:
def extract_budget_data(lines):
    data = []

    for line in lines:
        num = re.findall(r'-?[\d,.]+%?', line)

        if len(num) >= 4:
            num = num[:5]

            category = re.sub(r'-?[\d,.]+%?', "", line).strip()

            data.append([category] + num)

    df = pd.DataFrame(data, columns=[
        "Category",
        "Actual_2020-21",
        "Budgeted_2021-22",
        "Revised_2021-22",
        "Budgeted_2022-23",
        "Change_From_Previous_Year"
    ])
   
    df = df.replace({",": "", "%": ""}, regex=True)
   
    return df

budget_22_23 = extract_budget_data(lines)
budget_22_23["year"] = "2022-23"


budget_22_23.iloc[12,0]= "Revenue Deficit(% of GDP)"
budget_22_23.iloc[14,0]= "Fiscal Deficit(% of GDP)"
budget_22_23.iloc[16,0]= "Primary Deficit(% of GDP)"


budget_22_23 =budget_22_23.drop(index=0)

budget_22_23

,Category,Actual_2020-21,Budgeted_2021-22,Revised_2021-22,Budgeted_2022-23,Change_From_Previous_Year,year
1,Revenue Expenditure,3083519,2929000,3167289,3194663,0.9,2022-23
2,Capital Expenditure,426317,554236,602711,750246,24.5,2022-23
3,Capital Outlay,315826,513862,547457,610189,11.5,2022-23
4,Loans and Advances,110491,40374,55255,140057,153.5,2022-23
5,Total Expenditure,3509836,3483236,3770000,3944909,4.6,2022-23
6,Revenue Receipts,1633920,1788424,2078936,2204422,6.0,2022-23
7,Capital Receipts,57625,188000,99975,79291,-20.7,2022-23
8,Recoveries of Loans,19729,13000,21975,14291,-35.0,2022-23
9,Other receipts (including disinvestments),37897,175000,78000,65000,NaN,2022-23
10,Total Receipts (excluding borrowings),1691545,1976424,2178911,2283713,4.8,2022-23
11,Revenue Deficit,1449599,1140576,1088352,990241,-9.0,2022-23
12,Revenue Deficit(% of GDP),7.3,5.1,4.7,3.8,NaN,2022-23
13,Fiscal Deficit,1818291,1506812,1591089,1661196,4.4,2022-23
14,Fiscal Deficit(% of GDP),9.2,6.8,6.9,6.4,NaN,2022-23
15,Primary Deficit,1138422,697111,777298,720545,-7.3,2022-23
16,Primary Deficit(% of GDP),5.8,3.1,3.3,2.8,NaN,2022-23

In [60]:
with pdfplumber.open(os.path.join(pdfpath, "Union_Budget_2023-24.pdf")) as pdf:

    page = pdf.pages[2]
    text = page.extract_text()

lines = text.split("\n")
lines = lines[22:42]
lines

budget_23_24 = extract_budget_data(lines)
budget_23_24["year"] = "2023-24"
budget_23_24.rename(columns={
    "Actuals_2020-21":"Actual_2021-22",
     "Budgeted_2021-22":"Budgeted_2022-23",
     "Revised_2021-22":"Revised_2022-23",
     "Budgeted_2022-23":"Budgeted_2023-24",
    "Change":"Change_From_Previous_Year"}, inplace=True)

budget_23_24.iloc[12,0]= "Revenue Deficit(% of GDP)"
budget_23_24.iloc[14,0]= "Fiscal Deficit(% of GDP)"
budget_23_24.iloc[16,0]= "Primary Deficit(% of GDP)"

budget_23_24 =budget_23_24.drop(index=0)



budget_23_24

,Category,Actual_2020-21,Budgeted_2022-23,Revised_2022-23,Budgeted_2023-24,Change_From_Previous_Year,year
1,Revenue Expenditure,3200926,3194663,3458959,3502136,1.2,2023-24
2,Capital Expenditure,592874,750246,728274,1000961,37.4,2023-24
3,Capital Outlay,534499,610189,620204,837127,35.0,2023-24
4,Loans and Advances,58376,140057,108070,163834,51.6,2023-24
5,Total Expenditure,3793801,3944909,4187232,4503097,7.5,2023-24
6,Revenue Receipts,2169905,2204422,2348413,2632281,12.1,2023-24
7,Capital Receipts,39375,79291,83500,84000,0.6,2023-24
8,Recoveries of Loans,24737,14291,23500,23000,-2.1,2023-24
9,Other receipts (including disinvestments),14638,65000,60000,61000,NaN,2023-24
10,Total Receipts (excluding borrowings),2209280,2283713,2431913,2716281,11.7,2023-24
11,Revenue Deficit,1031021,990241,1110546,869855,-21.7,2023-24
12,Revenue Deficit(% of GDP),4.4,3.8,4.1,2.9,-29.3,2023-24
13,Fiscal Deficit,1584521,1661196,1755319,1786816,1.8,2023-24
14,Fiscal Deficit(% of GDP),6.7,6.4,6.4,5.9,-7.8,2023-24
15,Primary Deficit,779022,720545,814668,706845,-13.2,2023-24
16,Primary Deficit(% of GDP),3.3,2.8,3.0,2.3,-23.3,2023-24

In [61]:
with pdfplumber.open(os.path.join(pdfpath, "Union_Budget_2024-25.pdf")) as pdf:

    page = pdf.pages[2]
    text = page.extract_text()

lines = text.split("\n")
lines = lines[20:41]
lines

budget_24_25 = extract_budget_data(lines)
budget_24_25.rename(columns={
    "Actuals_2020-21":"Actual_2022-23",
     "Budgeted_2021-22":"Budgeted_2023-24",
     "Revised_2021-22":"Revised_2023-24",
     "Budgeted_2022-23":"Budgeted_2024-25",
    "Change":"Change_From_Previous_Year"}, inplace=True)

budget_24_25["year"] = "2024-25"

budget_24_25.iloc[12,0]= "Revenue Deficit(% of GDP)"
budget_24_25.iloc[14,0]= "Fiscal Deficit(% of GDP)"
budget_24_25.iloc[16,0]= "Primary Deficit(% of GDP)"

budget_24_25 =budget_24_25.drop(index=0)

 
budget_24_25

,Category,Actual_2020-21,Budgeted_2023-24,Revised_2023-24,Budgeted_2024-25,Change_From_Previous_Year,year
1,Revenue Expenditure,3453132,3502136,3494036,3709401,6.2,2024-25
2,Capital Expenditure,740025,1000961,948506,1111111,17.1,2024-25
3,Capital Outlay,624757,837127,787411,918695,16.7,2024-25
4,Loans and Advances,115268,163834,161095,192416,19.4,2024-25
5,Total Expenditure,4193157,4503097,4442542,4820512,8.5,2024-25
6,Revenue Receipts,2383206,2632281,2728412,3129200,14.7,2024-25
7,Capital Receipts,72196,84000,60461,78000,29.0,2024-25
8,Recoveries of Loans*,26161,23000,27338,28000,2.4,2024-25
9,Other receipts (including disinvestments)*,46035,61000,33123,50000,51.0,2024-25
10,Total Receipts (excluding borrowings),2455402,2716281,2788872,3207200,15.0,2024-25
11,Revenue Deficit,1069926,869855,765624,580201,-24.2,2024-25
12,Revenue Deficit(% of GDP),3.9,2.9,2.6,1.8,NaN,2024-25
13,Fiscal Deficit,1737755,1786816,1653670,1613312,-2.4,2024-25
14,Fiscal Deficit(% of GDP),6.4,5.9,5.6,4.9,NaN,2024-25
15,Primary Deficit,809238,706845,589799,450372,-23.6,2024-25
16,Primary Deficit(% of GDP),3.0,2.3,2.0,1.4,NaN,2024-25

In [62]:
with pdfplumber.open(os.path.join(pdfpath, "Union_Budget_2025-26.pdf")) as pdf:

    page = pdf.pages[2]
    text = page.extract_text()

lines = text.split("\n")
lines = lines[20:40]
lines

budget_25_26 = extract_budget_data(lines)
budget_25_26.rename(columns={
    "Actuals_2020-21":"Actual_2023-24",
     "Budgeted_2021-22":"Budgeted_2024-25",
     "Revised_2021-22":"Revised_2024-25",
     "Budgeted_2022-23":"Budgeted_2025-26",
    "Change":"Change_From_Previous_Year"}, inplace=True)

budget_25_26["year"] = "2025-26"

budget_25_26.iloc[12,0]= "Revenue Deficit(% of GDP)"
budget_25_26.iloc[14,0]= "Fiscal Deficit(% of GDP)"
budget_25_26.iloc[16,0]= "Primary Deficit(% of GDP)"


budget_25_26 =budget_25_26.drop(index=0)
  
budget_25_26

,Category,Actual_2020-21,Budgeted_2024-25,Revised_2024-25,Budgeted_2025-26,Change_From_Previous_Year,year
1,Revenue Expenditure,3494252,3709401,3698058,3944255,6.7,2025-26
2,Capital Expenditure,949195,1111111,1018429,1121090,10.1,2025-26
3,Capital Outlay,788100,918695,847736,895246,5.6,2025-26
4,Loans and Advances,161095,192416,170693,225844,32.3,2025-26
5,Total Expenditure,4443447,4820512,4716487,5065345,7.4,2025-26
6,Revenue Receipts,2729036,3129200,3087960,3420409,10.8,2025-26
7,Capital Receipts,59768,78000,59000,76000,28.8,2025-26
8,Recoveries of Loans,26646,28000,26000,29000,11.5,2025-26
9,Other receipts (including disinvestments),33122,50000,33000,47000,42.4,2025-26
10,Total Receipts (excluding borrowings),2788804,3207200,3146960,3496409,11.1,2025-26
11,Revenue Deficit,765216,580201,610098,523846,-14.1,2025-26
12,Revenue Deficit(% of GDP),2.6,1.8,1.9,1.5,NaN,2025-26
13,Fiscal Deficit,1654643,1613312,1569527,1568936,0.0,2025-26
14,Fiscal Deficit(% of GDP),5.6,4.9,4.8,4.4,NaN,2025-26
15,Primary Deficit,590771,450372,431587,292598,-32.2,2025-26
16,Primary Deficit(% of GDP),2.0,1.4,1.3,0.8,NaN,2025-26

In [63]:
with pdfplumber.open(os.path.join(pdfpath, "Union_Budget_2026-27.pdf")) as pdf:

    page = pdf.pages[2]
    text = page.extract_text()

lines = text.split("\n")
lines = lines[19:38]
lines

budget_26_27 = extract_budget_data(lines)
budget_26_27.rename(columns={
    "Actuals_2020-21":"Actual_2024-25",
     "Budgeted_2021-22":"Budgeted_2025-26",
     "Revised_2021-22":"Revised_2025-26",
     "Budgeted_2022-23":"Budgeted_2026-27",
    "Change":"Change_From_Previous_Year"}, inplace=True)

budget_26_27["year"] = "2026-27"

budget_26_27.iloc[12,0]= "Revenue Deficit(% of GDP)"
budget_26_27.iloc[14,0]= "Fiscal Deficit(% of GDP)"
budget_26_27.iloc[16,0]= "Primary Deficit(% of GDP)"


budget_26_27 =budget_26_27.drop(index=0)

budget_26_27

,Category,Actual_2020-21,Budgeted_2025-26,Revised_2025-26,Budgeted_2026-27,Change_From_Previous_Year,year
1,Revenue Expenditure,3600914,3944255,3869087,4125494,6.6,2026-27
2,Capital Expenditure,1051953,1121090,1095755,1221821,11.5,2026-27
3,Capital Outlay,855244,895245,887364,943042,6.3,2026-27
4,Loans and Advances,196710,225844,208391,278780,33.8,2026-27
5,Total Expenditure,4652867,5065345,4964842,5347315,7.7,2026-27
6,Revenue Receipts,3036619,3420409,3342323,3533150,5.7,2026-27
7,Capital Receipts,41818,76000,64027,118397,84.9,2026-27
8,Recoveries of Loans,24617,29000,30190,38397,27.2,2026-27
9,Disinvestments,17202,47000,33837,80000,136.4,2026-27
10,Total Receipts (excluding borrowings),3078436,3496409,3406350,3651547,7.2,2026-27
11,Revenue Deficit,564296,523846,526764,592344,12.4,2026-27
12,Revenue Deficit(% of GDP),1.7,1.5,1.5,1.5,NaN,2026-27
13,Fiscal Deficit,1574431,1568936,1558492,1695768,8.8,2026-27
14,Fiscal Deficit(% of GDP),4.8,4.4,4.4,4.3,NaN,2026-27
15,Primary Deficit,458856,292598,284154,291796,2.7,2026-27
16,Primary Deficit(% of GDP),1.4,0.8,0.8,0.7,NaN,2026-27

In [70]:
def to_df(obj):
    if isinstance(obj, pd.io.formats.style.Styler):
        return obj.data
    return obj

# Convert all 6
budget_21_22 = to_df(budget_21_22)
budget_22_23 = to_df(budget_22_23)
budget_23_24 = to_df(budget_23_24)
budget_24_25 = to_df(budget_24_25)
budget_25_26 = to_df(budget_25_26)
budget_26_27 = to_df(budget_26_27)

budget_21_22.columns = ["Category","Actual","Budgeted","Revised","Next_Budget","Change","Year"]

budget_22_23.columns = ["Category","Actual","Budgeted","Revised","Next_Budget","Change","Year"]

budget_23_24.columns = ["Category","Actual","Budgeted","Revised","Next_Budget","Change","Year"]

budget_24_25.columns = ["Category","Actual","Budgeted","Revised","Next_Budget","Change","Year"]

budget_25_26.columns = ["Category","Actual","Budgeted","Revised","Next_Budget","Change","Year"]

budget_26_27.columns = ["Category","Actual","Budgeted","Revised","Next_Budget","Change","Year"]



merged_budget = pd.concat(
    [budget_21_22, budget_22_23, budget_23_24,
     budget_24_25, budget_25_26, budget_26_27],
    ignore_index=True
)

# For Diplaying it in the aligned Center manner

merged_budget.style.set_properties(**{'text-align': 'center'}) \
    .set_table_styles([{
        'selector': 'th',
        'props': [('text-align', 'center')]
    }])

# merged_budget.iloc[:55]

# print("Shape:", merged_budget.shape)
# # Should be (96, 7) as 96 rows and 7 columns

# print("\nRows per year:")
# print(merged_budget['Year'].value_counts().sort_index())
# # Should show 16 for each year

# print("\nFirst few rows:")
# print(merged_budget.head(5).to_string())

In [91]:
# DATA CLEANING 


merged_budget['Category'] = merged_budget['Category'].replace({
    'Capital outlay'                              : 'Capital Outlay',
    'Loans'                                       : 'Loans and Advances',
    'Loans and Advances and Advances'             : 'Loans and Advances',
    'Recoveries of Loans'                         : 'Recoveries of Loans and Advances',
    'Recoveries of Loans*'                        : 'Recoveries of Loans and Advances',
    'Other receipts (including disinvestments)*'  : 'Other receipts (including disinvestments)',
    'Disinvestments'                              : 'Other receipts (including disinvestments)',
    'Total Receipts (without borrowings)'         : 'Total Receipts (excluding borrowings)'
})

merged_budget['metric_type'] = merged_budget['Category'].apply(
    lambda x: 'Gdp_ratio' if '% of GDP' in x else 'Amount'
)


merged_budget.replace('N/A', np.nan, inplace=True)
merged_budget.replace('nan', np.nan, inplace=True)

#merged_budget.dtypes

num_cols = ['Actual', 'Budgeted', 'Revised', 'Next_Budget', 'Change']
for col in num_cols:
    merged_budget[col] = pd.to_numeric(merged_budget[col], errors='coerce')

merged_budget.iloc[:55]

,Category,Actual,Budgeted,Revised,Next_Budget,Change,Year,metric_type,group
0,Revenue Expenditure,2350604.0,2630145.0,3011142.0,2929000.0,12.0,2021-22,Amount,Expenditure
1,Capital Expenditure,335726.0,412085.0,439163.0,554236.0,29.0,2021-22,Amount,Expenditure
2,Capital Outlay,311312.0,380322.0,332247.0,513862.0,29.0,2021-22,Amount,Expenditure
3,Loans and Advances,24414.0,31763.0,106916.0,40374.0,29.0,2021-22,Amount,Expenditure
4,Total Expenditure,2686330.0,3042230.0,3450305.0,3483236.0,14.0,2021-22,Amount,Expenditure
5,Revenue Receipts,1684059.0,2020926.0,1555153.0,1788424.0,3.0,2021-22,Amount,Receipts
6,Capital Receipts,68620.0,224967.0,46497.0,188000.0,66.0,2021-22,Amount,Receipts
7,Recoveries of Loans and Advances,18316.0,14967.0,14497.0,13000.0,-16.0,2021-22,Amount,Receipts
8,Other receipts (including disinvestments),50304.0,210000.0,32000.0,175000.0,87.0,2021-22,Amount,Receipts
9,Total Receipts (excluding borrowings),1752679.0,2245893.0,1601650.0,1976424.0,6.0,2021-22,Amount,Receipts
10,Revenue Deficit,666545.0,609219.0,1455989.0,1140576.0,31.0,2021-22,Amount,Deficit
11,Revenue Deficit(% of GDP),3.3,2.7,7.5,5.1,NaN,2021-22,Gdp_ratio,Deficit
12,Fiscal Deficit,933651.0,796337.0,1848655.0,1506812.0,27.0,2021-22,Amount,Deficit
13,Fiscal Deficit(% of GDP),4.6,3.5,9.5,6.8,NaN,2021-22,Gdp_ratio,Deficit
14,Primary Deficit,321581.0,88134.0,1155755.0,697111.0,47.0,2021-22,Amount,Deficit
15,Primary Deficit(% of GDP),1.6,0.4,5.9,3.1,NaN,2021-22,Gdp_ratio,Deficit
16,Revenue Expenditure,3083519.0,2929000.0,3167289.0,3194663.0,0.9,2022-23,Amount,Expenditure
17,Capital Expenditure,426317.0,554236.0,602711.0,750246.0,24.5,2022-23,Amount,Expenditure
18,Capital Outlay,315826.0,513862.0,547457.0,610189.0,11.5,2022-23,Amount,Expenditure
19,Loans and Advances,110491.0,40374.0,55255.0,140057.0,153.5,2022-23,Amount,Expenditure
20,Total Expenditure,3509836.0,3483236.0,3770000.0,3944909.0,4.6,2022-23,Amount,Expenditure
21,Revenue Receipts,1633920.0,1788424.0,2078936.0,2204422.0,6.0,2022-23,Amount,Receipts
22,Capital Receipts,57625.0,188000.0,99975.0,79291.0,-20.7,2022-23,Amount,Receipts
23,Recoveries of Loans and Advances,19729.0,13000.0,21975.0,14291.0,-35.0,2022-23,Amount,Receipts
24,Other receipts (including disinvestments),37897.0,175000.0,78000.0,65000.0,NaN,2022-23,Amount,Receipts
25,Total Receipts (excluding borrowings),1691545.0,1976424.0,2178911.0,2283713.0,4.8,2022-23,Amount,Receipts
26,Revenue Deficit,1449599.0,1140576.0,1088352.0,990241.0,-9.0,2022-23,Amount,Deficit
27,Revenue Deficit(% of GDP),7.3,5.1,4.7,3.8,NaN,2022-23,Gdp_ratio,Deficit
28,Fiscal Deficit,1818291.0,1506812.0,1591089.0,1661196.0,4.4,2022-23,Amount,Deficit
29,Fiscal Deficit(% of GDP),9.2,6.8,6.9,6.4,NaN,2022-23,Gdp_ratio,Deficit
30,Primary Deficit,1138422.0,697111.0,777298.0,720545.0,-7.3,2022-23,Amount,Deficit
31,Primary Deficit(% of GDP),5.8,3.1,3.3,2.8,NaN,2022-23,Gdp_ratio,Deficit
32,Revenue Expenditure,3200926.0,3194663.0,3458959.0,3502136.0,1.2,2023-24,Amount,Expenditure
33,Capital Expenditure,592874.0,750246.0,728274.0,1000961.0,37.4,2023-24,Amount,Expenditure
34,Capital Outlay,534499.0,610189.0,620204.0,837127.0,35.0,2023-24,Amount,Expenditure
35,Loans and Advances,58376.0,140057.0,108070.0,163834.0,51.6,2023-24,Amount,Expenditure
36,Total Expenditure,3793801.0,3944909.0,4187232.0,4503097.0,7.5,2023-24,Amount,Expenditure
37,Revenue Receipts,2169905.0,2204422.0,2348413.0,2632281.0,12.1,2023-24,Amount,Receipts
38,Capital Receipts,39375.0,79291.0,83500.0,84000.0,0.6,2023-24,Amount,Receipts
39,Recoveries of Loans and Advances,24737.0,14291.0,23500.0,23000.0,-2.1,2023-24,Amount,Receipts
40,Other receipts (including disinvestments),14638.0,65000.0,60000.0,61000.0,NaN,2023-24,Amount,Receipts
41,Total Receipts (excluding borrowings),2209280.0,2283713.0,2431913.0,2716281.0,11.7,2023-24,Amount,Receipts
42,Revenue Deficit,1031021.0,990241.0,1110546.0,869855.0,-21.7,2023-24,Amount,Deficit
43,Revenue Deficit(% of GDP),4.4,3.8,4.1,2.9,-29.3,2023-24,Gdp_ratio,Deficit
44,Fiscal Deficit,1584521.0,1661196.0,1755319.0,1786816.0,1.8,2023-24,Amount,Deficit
45,Fiscal Deficit(% of GDP),6.7,6.4,6.4,5.9,-7.8,2023-24,Gdp_ratio,Deficit
46,Primary Deficit,779022.0,720545.0,814668.0,706845.0,-13.2,2023-24,Amount,Deficit
47,Primary Deficit(% of GDP),3.3,2.8,3.0,2.3,-23.3,2023-24,Gdp_ratio,Deficit
48,Revenue Expenditure,3453132.0,3502136.0,3494036.0,3709401.0,6.2,2024-25,Amount,Expenditure
49,Capital Expenditure,740025.0,1000961.0,948506.0,1111111.0,17.1,2024-25,Amount,Expenditure
50,Capital Outlay,624757.0,837127.0,787411.0,918695.0,16.7,2024-25,Amount,Expenditure
51,Loans and Advances,115268.0,163834.0,161095.0,192416.0,19.4,2024-25,Amount,Expenditure
52,Total Expenditure,4193157.0,4503097.0,4442542.0,4820512.0,8.5,2024-25,Amount,Expenditure
53,Revenue Receipts,2383206.0,2632281.0,2728412.0,3129200.0,14.7,2024-25,Amount,Receipts
54,Capital Receipts,72196.0,84000.0,60461.0,78000.0,29.0,2024-25,Amount,Receipts

In [93]:
def classify(category):
    if '% of GDP' in category:
        return 'Deficit'
    elif 'Receipts' in category or 'Recoveries' in category or 'Disinvestment' in category or 'disinvestment' in category or 'Other receipts' in category:
        return 'Receipts'
    elif 'Expenditure' in category or 'Outlay' in category or 'Loans and Advances' in category:
        return 'Expenditure'
    elif 'Deficit' in category:
        return 'Deficit'
    else:
        return 'Other'

merged_budget['group'] = merged_budget['Category'].apply(classify)

merged_budget = merged_budget.reset_index(drop=True)

In [94]:
#merged_budget = merged_budget.sort_values(["Year","Category"])
# merged_budget = merged_budget.drop_duplicates(
#     subset=["Category","Year"]
# )
# merged_budget.iloc[:60]
print("Shape:", merged_budget.shape)
print("\nData types:")
print(merged_budget.dtypes)
print("\nNull values:")
print(merged_budget.isnull().sum())
print("\nCategory names:")
print(merged_budget['Category'].unique())

Shape: (96, 9)

Data types:
Category           str
Actual         float64
Budgeted       float64
Revised        float64
Next_Budget    float64
Change         float64
Year               str
metric_type        str
group              str
dtype: object

Null values:
Category        0
Actual          0
Budgeted        0
Revised         0
Next_Budget     0
Change         17
Year            0
metric_type     0
group           0
dtype: int64

Category names:
<StringArray>
[                      'Revenue Expenditure',
                       'Capital Expenditure',
                            'Capital Outlay',
                        'Loans and Advances',
                         'Total Expenditure',
                          'Revenue Receipts',
                          'Capital Receipts',
          'Recoveries of Loans and Advances',
 'Other receipts (including disinvestments)',
     'Total Receipts (excluding borrowings)',
                           'Revenue Deficit',
                 'Revenue Deficit(% of GDP)',
                            'Fiscal Deficit',
                  'Fiscal Deficit(% of GDP)',
                           'Primary Deficit',
                 'Primary Deficit(% of GDP)']
Length: 16, dtype: str

In [95]:
print(merged_budget[merged_budget['Change'].isna()][['Category', 'Year']])

                                     Category     Year
11                  Revenue Deficit(% of GDP)  2021-22
13                   Fiscal Deficit(% of GDP)  2021-22
15                  Primary Deficit(% of GDP)  2021-22
24  Other receipts (including disinvestments)  2022-23
27                  Revenue Deficit(% of GDP)  2022-23
29                   Fiscal Deficit(% of GDP)  2022-23
31                  Primary Deficit(% of GDP)  2022-23
40  Other receipts (including disinvestments)  2023-24
59                  Revenue Deficit(% of GDP)  2024-25
61                   Fiscal Deficit(% of GDP)  2024-25
63                  Primary Deficit(% of GDP)  2024-25
75                  Revenue Deficit(% of GDP)  2025-26
77                   Fiscal Deficit(% of GDP)  2025-26
79                  Primary Deficit(% of GDP)  2025-26
91                  Revenue Deficit(% of GDP)  2026-27
93                   Fiscal Deficit(% of GDP)  2026-27
95                  Primary Deficit(% of GDP)  2026-27

In [98]:
path = "/Users/apple/Desktop/Data Science/Data Files"
merged_budget.to_csv(os.path.join(path,"Budget_Analysis"),index=False)

In [117]:
df = pd.read_csv("Budget_Analysis")
# df.loc[df['Category'].str.contains('% of GDP', na=False), 'Change'] = np.nan

# mask = (
#     df['Change'].isna() &
#     ~df['Category'].str.contains('% of GDP', na=False)
# )

# # ── Step 3: YOU WERE MISSING THIS! Apply CAGR formula
# df.loc[mask, 'Change'] = (
#     (df.loc[mask, 'Next_Budget'] /
#      df.loc[mask, 'Actual']) ** (1/2) - 1
# ) * 100
# df['Change'] = df['Change'].round(1)

# # ── Step 4: Verify
# print("Shape:", df.shape)
# print("\nNaN in Change:")
# print(df[df['Change'].isna()][['Category', 'Year']])
# print("\nTotal NaN:", df['Change'].isna().sum())

df.iloc[:59]

,Category,Actual,Budgeted,Revised,Next_Budget,Change,Year,metric_type,group
0,Revenue Expenditure,2350604.0,2630145.0,3011142.0,2929000.0,12.0,2021-22,Amount,Expenditure
1,Capital Expenditure,335726.0,412085.0,439163.0,554236.0,29.0,2021-22,Amount,Expenditure
2,Capital Outlay,311312.0,380322.0,332247.0,513862.0,29.0,2021-22,Amount,Expenditure
3,Loans and Advances,24414.0,31763.0,106916.0,40374.0,29.0,2021-22,Amount,Expenditure
4,Total Expenditure,2686330.0,3042230.0,3450305.0,3483236.0,14.0,2021-22,Amount,Expenditure
5,Revenue Receipts,1684059.0,2020926.0,1555153.0,1788424.0,3.0,2021-22,Amount,Receipts
6,Capital Receipts,68620.0,224967.0,46497.0,188000.0,66.0,2021-22,Amount,Receipts
7,Recoveries of Loans and Advances,18316.0,14967.0,14497.0,13000.0,-16.0,2021-22,Amount,Receipts
8,Other receipts (including disinvestments),50304.0,210000.0,32000.0,175000.0,87.0,2021-22,Amount,Receipts
9,Total Receipts (excluding borrowings),1752679.0,2245893.0,1601650.0,1976424.0,6.0,2021-22,Amount,Receipts
10,Revenue Deficit,666545.0,609219.0,1455989.0,1140576.0,31.0,2021-22,Amount,Deficit
11,Revenue Deficit(% of GDP),3.3,2.7,7.5,5.1,NaN,2021-22,Gdp_ratio,Deficit
12,Fiscal Deficit,933651.0,796337.0,1848655.0,1506812.0,27.0,2021-22,Amount,Deficit
13,Fiscal Deficit(% of GDP),4.6,3.5,9.5,6.8,NaN,2021-22,Gdp_ratio,Deficit
14,Primary Deficit,321581.0,88134.0,1155755.0,697111.0,47.0,2021-22,Amount,Deficit
15,Primary Deficit(% of GDP),1.6,0.4,5.9,3.1,NaN,2021-22,Gdp_ratio,Deficit
16,Revenue Expenditure,3083519.0,2929000.0,3167289.0,3194663.0,0.9,2022-23,Amount,Expenditure
17,Capital Expenditure,426317.0,554236.0,602711.0,750246.0,24.5,2022-23,Amount,Expenditure
18,Capital Outlay,315826.0,513862.0,547457.0,610189.0,11.5,2022-23,Amount,Expenditure
19,Loans and Advances,110491.0,40374.0,55255.0,140057.0,153.5,2022-23,Amount,Expenditure
20,Total Expenditure,3509836.0,3483236.0,3770000.0,3944909.0,4.6,2022-23,Amount,Expenditure
21,Revenue Receipts,1633920.0,1788424.0,2078936.0,2204422.0,6.0,2022-23,Amount,Receipts
22,Capital Receipts,57625.0,188000.0,99975.0,79291.0,-20.7,2022-23,Amount,Receipts
23,Recoveries of Loans and Advances,19729.0,13000.0,21975.0,14291.0,-35.0,2022-23,Amount,Receipts
24,Other receipts (including disinvestments),37897.0,175000.0,78000.0,65000.0,NaN,2022-23,Amount,Receipts
25,Total Receipts (excluding borrowings),1691545.0,1976424.0,2178911.0,2283713.0,4.8,2022-23,Amount,Receipts
26,Revenue Deficit,1449599.0,1140576.0,1088352.0,990241.0,-9.0,2022-23,Amount,Deficit
27,Revenue Deficit(% of GDP),7.3,5.1,4.7,3.8,NaN,2022-23,Gdp_ratio,Deficit
28,Fiscal Deficit,1818291.0,1506812.0,1591089.0,1661196.0,4.4,2022-23,Amount,Deficit
29,Fiscal Deficit(% of GDP),9.2,6.8,6.9,6.4,NaN,2022-23,Gdp_ratio,Deficit
30,Primary Deficit,1138422.0,697111.0,777298.0,720545.0,-7.3,2022-23,Amount,Deficit
31,Primary Deficit(% of GDP),5.8,3.1,3.3,2.8,NaN,2022-23,Gdp_ratio,Deficit
32,Revenue Expenditure,3200926.0,3194663.0,3458959.0,3502136.0,1.2,2023-24,Amount,Expenditure
33,Capital Expenditure,592874.0,750246.0,728274.0,1000961.0,37.4,2023-24,Amount,Expenditure
34,Capital Outlay,534499.0,610189.0,620204.0,837127.0,35.0,2023-24,Amount,Expenditure
35,Loans and Advances,58376.0,140057.0,108070.0,163834.0,51.6,2023-24,Amount,Expenditure
36,Total Expenditure,3793801.0,3944909.0,4187232.0,4503097.0,7.5,2023-24,Amount,Expenditure
37,Revenue Receipts,2169905.0,2204422.0,2348413.0,2632281.0,12.1,2023-24,Amount,Receipts
38,Capital Receipts,39375.0,79291.0,83500.0,84000.0,0.6,2023-24,Amount,Receipts
39,Recoveries of Loans and Advances,24737.0,14291.0,23500.0,23000.0,-2.1,2023-24,Amount,Receipts
40,Other receipts (including disinvestments),14638.0,65000.0,60000.0,61000.0,NaN,2023-24,Amount,Receipts
41,Total Receipts (excluding borrowings),2209280.0,2283713.0,2431913.0,2716281.0,11.7,2023-24,Amount,Receipts
42,Revenue Deficit,1031021.0,990241.0,1110546.0,869855.0,-21.7,2023-24,Amount,Deficit
43,Revenue Deficit(% of GDP),4.4,3.8,4.1,2.9,-29.3,2023-24,Gdp_ratio,Deficit
44,Fiscal Deficit,1584521.0,1661196.0,1755319.0,1786816.0,1.8,2023-24,Amount,Deficit
45,Fiscal Deficit(% of GDP),6.7,6.4,6.4,5.9,-7.8,2023-24,Gdp_ratio,Deficit
46,Primary Deficit,779022.0,720545.0,814668.0,706845.0,-13.2,2023-24,Amount,Deficit
47,Primary Deficit(% of GDP),3.3,2.8,3.0,2.3,-23.3,2023-24,Gdp_ratio,Deficit
48,Revenue Expenditure,3453132.0,3502136.0,3494036.0,3709401.0,6.2,2024-25,Amount,Expenditure
49,Capital Expenditure,740025.0,1000961.0,948506.0,1111111.0,17.1,2024-25,Amount,Expenditure
50,Capital Outlay,624757.0,837127.0,787411.0,918695.0,16.7,2024-25,Amount,Expenditure
51,Loans and Advances,115268.0,163834.0,161095.0,192416.0,19.4,2024-25,Amount,Expenditure
52,Total Expenditure,4193157.0,4503097.0,4442542.0,4820512.0,8.5,2024-25,Amount,Expenditure
53,Revenue Receipts,2383206.0,2632281.0,2728412.0,3129200.0,14.7,2024-25,Amount,Receipts
54,Capital Receipts,72196.0,84000.0,60461.0,78000.0,29.0,2024-25,Amount,Receipts
55,Recoveries of Loans and Advances,26161.0,23000.0,27338.0,28000.0,2.4,2024-25,Amount,Receipts
56,Other receipts (including disinvestments),46035.0,61000.0,33123.0,50000.0,51.0,2024-25,Amount,Receipts
57,Total Receipts (excluding borrowings),2455402.0,2716281.0,2788872.0,3207200.0,15.0,2024-25,Amount,Receipts
58,Revenue Deficit,1069926.0,869855.0,765624.0,580201.0,-24.2,2024-25,Amount,Deficit

In [118]:
path = "/Users/apple/Desktop/Data Science/Data Files"
df.to_csv(os.path.join(path,"Indian_Budget_Analysis"),index=False)